language: python
python:
  - "2.7"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64
 #    - sudo: required
 #      services:
 #        - docker
 #      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
 #           PRE_CMD=linux32
 #           PLAT=manylinux1_i686

addons:
 apt_packages:
   - swig

install:
  - docker pull $DOCKER_IMAGE
  - pip install -r requirements.txt

script:
  - wget -O - https://downloads.sourceforge.net/swig/swig-4.0.1.tar.gz | tar xzf -
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
  - PYTHONPATH=`pwd`/tmp-test-install/lib/python2.7/site-packages/  make test

